# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.srcs/sources_1/ip/layer2_weights_bram/layer2_weights_bram.xci
# IP: The module: 'layer2_weights_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.gen/sources_1/ip/layer2_weights_bram/layer2_weights_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layer2_weights_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.srcs/sources_1/ip/layer2_weights_bram/layer2_weights_bram.xci
# IP: The module: 'layer2_weights_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.gen/sources_1/ip/layer2_weights_bram/layer2_weights_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'layer2_weights_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
