# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.srcs/sources_1/ip/image_bram_ip/image_bram_ip.xci
# IP: The module: 'image_bram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.gen/sources_1/ip/image_bram_ip/image_bram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_bram_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.srcs/sources_1/ip/image_bram_ip/image_bram_ip.xci
# IP: The module: 'image_bram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.gen/sources_1/ip/image_bram_ip/image_bram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_bram_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
