# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.srcs/sources_1/ip/uart_ila/uart_ila.xci
# IP: The module: 'uart_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.gen/sources_1/ip/uart_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_ila'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.gen/sources_1/ip/uart_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.gen/sources_1/ip/uart_ila/uart_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.srcs/sources_1/ip/uart_ila/uart_ila.xci
# IP: The module: 'uart_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.gen/sources_1/ip/uart_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.gen/sources_1/ip/uart_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/Fashion_MNIST_MLP/Fashion_MNIST_MLP.gen/sources_1/ip/uart_ila/uart_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
